const translations = {
    pl: {
        headerTitle: "Elektryka do Aut Zabytkowych",
        navHome: "Strona główna",
        navGallery: "Galeria",
        navContact: "Kontakt",
        navPrivacy: "Polityka prywatności",
        homeTitle: "Oferowane usługi",
        homeContent1: "<b>Z ponad dziesięcioletnim doświadczeniem w branży</b>, specjalizuję się w projektowaniu i montażu niestandardowych wiązek elektrycznych do zabytkowych samochodów, zapewniając nie tylko funkcjonalność, ale także zachowanie autentycznego charakteru pojazdu. Oferuję kompleksowe usługi obejmujące projektowanie, produkcję i instalację wysokiej jakości wiązek elektrycznych do najbardziej wymagających zabytkowych aut.",
        homeContent2: "Dzięki zdobytym umiejętnościom oraz ciągłemu rozwojowi w dziedzinie nowoczesnych technologii elektrycznych, mogę zaoferować kompleksowe usługi obejmujące projektowanie, produkcję i instalację wysokiej jakości wiązek elektrycznych do najbardziej wymagających zabytkowych aut. Każda wiązka elektryczna, którą wykonuję, podlega starannemu procesowi kontroli jakości.",
        galleryTitle: "Galeria",
        contactTitle: "Kontakt",
        contactName: "Imię:",
        contactEmail: "E-mail:",
        contactMessage: "Wiadomość:",
        contactSend: "Wyślij",
        contactAddress: "Adres: ",
        contactPhone: "Numer telefonu: ",
        contactEmailLabel: "Adres e-mail: ",
        cookieMessage: "Ta strona używa plików cookies, aby zapewnić najlepszą jakość korzystania z naszej strony. Kontynuując przeglądanie tej witryny, zgadzasz się na użycie plików cookies.",
        cookieAccept: "Akceptuję",
        textPrivacy0: "Niniejsza polityka prywatności określa zasady przetwarzania i ochrony danych osobowych przekazanych przez użytkowników w związku z korzystaniem z usług oferowanych przez stronę internetową Elektryka do Aut Zabytkowych.",
        textPrivacy1: "Administratorem danych osobowych jest [Nazwa Firmy], z siedzibą w [Adres], NIP: [NIP], REGON: [REGON], który dba o prawidłowe przetwarzanie i ochronę danych osobowych użytkowników.",
        textPrivacy2: "Cele przetwarzania danych. Dane osobowe przetwarzane są w celu świadczenia usług zgodnie z zamówieniem użytkownika. Użytkownik może być informowany o nowościach i promocjach dotyczących oferowanych usług, jeśli wyrazi na to zgodę.",
        textPrivacy3: "Podstawa prawna przetwarzania danych. Przetwarzanie danych odbywa się na podstawie zgody użytkownika lub jest niezbędne do wykonania umowy. Użytkownik ma prawo wycofania zgody w dowolnym momencie.",
        textPrivacy4: "Ochrona danych osobowych. Dane osobowe są chronione przed nieuprawnionym dostępem, utratą lub zniszczeniem. Wszelkie dane osobowe są przechowywane i przetwarzane zgodnie z obowiązującymi przepisami prawa.",
        textPrivacy5: "Prawa użytkownika. Użytkownik ma prawo dostępu do swoich danych osobowych oraz ich poprawiania. Ma również prawo do żądania usunięcia danych osobowych, ograniczenia ich przetwarzania oraz przenoszenia danych.",
        textPrivacy6: "Kontakt. W sprawach dotyczących ochrony danych osobowych można kontaktować się z administratorem pod adresem [Adres kontaktowy] lub mailowo pod adresem [Adres e-mail].",
    },
    en: {
        headerTitle: "Vintage Car Electrical Restoration",
        navHome: "Home",
        navGallery: "Gallery",
        navContact: "Contact",
        navPrivacy: "Privacy Policy",
        homeTitle: "Services Offered",
        homeContent1: "<b>With over ten years of experience in the industry</b>, I specialize in designing and installing custom electrical harnesses for vintage cars, ensuring not only functionality but also preserving the authentic character of the vehicle. I offer comprehensive services including design, production, and installation of high-quality electrical harnesses for the most demanding vintage cars.",
        homeContent2: "Thanks to the skills acquired and continuous development in the field of modern electrical technologies, I can offer comprehensive services including design, production, and installation of high-quality electrical harnesses for the most demanding vintage cars. Every electrical harness I make undergoes a thorough quality control process.",
        galleryTitle: "Gallery",
        contactTitle: "Contact",
        contactName: "Name:",
        contactEmail: "Email:",
        contactMessage: "Message:",
        contactSend: "Send",
        contactAddress: "Address: ",
        contactPhone: "Phone number: ",
        contactEmailLabel: "Email address: ",
        cookieMessage: "This website uses cookies to ensure you get the best experience on our website. By continuing to browse the site, you agree to our use of cookies.",
        cookieAccept: "Accept",
        textPrivacy0: "This privacy policy outlines the principles of processing and protecting personal data provided by users in connection with the use of services offered by the website Vintage Car Electrical Services.",
        textPrivacy1: "Data Controller. [Company Name], located at [Address], VAT: [VAT], REGON: [REGON], is responsible for proper processing and protection of user's personal data.",
        textPrivacy2: "Purposes of Data Processing. Personal data is processed to provide services according to the user's order. Users may be informed about news and promotions regarding the services offered, if they consent to it.",
        textPrivacy3: "Legal Basis for Data Processing. Data processing is based on the user's consent or is necessary for the performance of a contract. Users have the right to withdraw their consent at any time.",
        textPrivacy4: "Data Protection. Personal data is protected against unauthorized access, loss, or destruction. All personal data is stored and processed in accordance with applicable laws.",
        textPrivacy5: "User Rights. Users have the right to access and correct their personal data. They also have the right to request the deletion of personal data, restriction of processing, and data portability.",
        textPrivacy6: "Contact. For matters related to the protection of personal data, users can contact the data controller at [Contact Address] or via email at [Email Address].",
    },
};
